# Data Preprocessing for Brawl Stars' Datasets

* Libraries:

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder
from sklearn.impute import SimpleImputer

---

</br>

# The Bests 200 Jessie's Players Dataframe

* Data import:

In [4]:
df_jessie = pd.read_csv("../data/raw/dataset/brawler_ranking/JESSIE_ranking.csv")

In [ ]:
df_jessie.head(10)

,Unnamed: 0,tag,name,nameColor,icon,trophies,rank,club
0,0,#VL0GPPJV,Physic Gear 5,0xfff9c908,28000014,1401,1,Eclipse üåñ
1,1,#2Y92C2Q8V,NOMAD|„Åã„Éº„Åö„ÄÇ‚ùÑ‚ùÑ,0xfff9c908,28000119,1399,2,NaN
2,2,#VLQPVPY,Naz‚ù§Ô∏èHyra,0xffff8afb,28000303,1399,3,Fenernaz√ße üíôüíõ
3,3,#JQVQYVY,Code: VTzim üåë,0xffff8afb,28000339,1309,4,Eclipse üåñ
4,4,#RRVVPG2Y,BrostaÂç°Êãâ,0xff1ba5f5,28000206,1307,5,vMoove
5,5,#89UPQJJVV,+BraboX üé©,0xffa8e132,28000236,1302,6,Ghost Teamüëª‚òî
6,6,#VYGVV08Q,üçÖdomates,0xffffffff,28000261,1302,7,NaN
7,7,#2Y2Y99GQR,VizeZ,0xffffffff,28000230,1302,8,Ex0tic-E-Sport
8,8,#8GV2CP2J8,‚òîZORLU‚òî,0xffcb5aff,28000003,1301,9,<c0>Ôº¨ÔºØÔºÆÔº•Ôº¨Ôºπ‚òÖ</c>
9,9,#2G90YQ9CQ,∏·µó·¥ç…™ Ä·¥Ä…¥·¥Ö…™…¥ ú·¥Ä·µáÀ¢‰π°,0xffa8e132,28000174,1301,10,W·¥è ü“ì …¢·¥Ä…¥…¢ üêæ

In [ ]:
df_jessie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  200 non-null    int64
 1   tag         200 non-null    object
 2   name        200 non-null    object
 3   nameColor   200 non-null    object
 4   icon        200 non-null    int64
 5   trophies    200 non-null    int64
 6   rank        200 non-null    int64
 7   club        188 non-null    object
dtypes: int64(4), object(4)
memory usage: 12.6+ KB

In [ ]:
df_jessie.describe

<bound method NDFrame.describe of      Unnamed: 0         tag             name   nameColor      icon  trophies  \
0             0   #VL0GPPJV    Physic Gear 5  0xfff9c908  28000014      1401
1             1  #2Y92C2Q8V     NOMAD|„Åã„Éº„Åö„ÄÇ‚ùÑ‚ùÑ  0xfff9c908  28000119      1399
2             2    #VLQPVPY        Naz‚ù§Ô∏èHyra  0xffff8afb  28000303      1399
3             3    #JQVQYVY    Code: VTzim üåë  0xffff8afb  28000339      1309
4             4   #RRVVPG2Y         BrostaÂç°Êãâ  0xff1ba5f5  28000206      1307
..          ...         ...              ...         ...       ...       ...
195         195   #2RG0LV02  STMN | Scofield  0xff4ddba2  28000136      1103
196         196    #VRRPQ2J      ·¥©·¥Ä ô ü·¥èÀ¢·µÉ·µà:')  0xffa8e132  28000018      1103
197         197  #2L80JP00L           Hillen  0xffff8afb  28000335      1103
198         198   #9LYQR9QC            Stas.  0xffff8afb  28000321      1103
199         199    #2JLVRQ9      STMN | Zhar  0xffa8e132  28000347      1103

     rank            club
0       1       Eclipse üåñ
1       2             NaN
2       3   Fenernaz√ße üíôüíõ
3       4       Eclipse üåñ
4       5          vMoove
..    ...             ...
195   196          vMoove
196   197          WOLFMX
197   198  Ex0tic-E-Sport
198   199      Affective.
199   200    STMN Esports

[200 rows x 8 columns]>

In [ ]:
# View the column names
print(df_jessie.columns)

Index(['Unnamed: 0', 'tag', 'name', 'nameColor', 'icon', 'trophies', 'rank',
       'club'],
      dtype='object')

---

* Data Cleaning:

In [5]:
# Check for missing values per column
null_values = df_jessie.isnull().sum()
print("Missing values per column:\n", null_values)

# Check for total missing values in the entire dataset
total_nulls = df_jessie.isnull().sum().sum()
print(f'Total missing values in the dataset: {total_nulls}')

Missing values per column:
 Unnamed: 0     0
tag            0
name           0
nameColor      0
icon           0
trophies       0
rank           0
club          12
dtype: int64
Total missing values in the dataset: 12

In [ ]:
# Check the percentage of missing values per column
null_percentage = (df_jessie.isnull().sum() / len(df_jessie)) * 100
print("Percentage of missing values per column:\n", null_percentage)

Percentage of missing values per column:
 Unnamed: 0    0.0
tag           0.0
name          0.0
nameColor     0.0
icon          0.0
trophies      0.0
rank          0.0
club          6.0
dtype: float64

In [6]:
# Replace null values in the 'club' column with "no-team-info"
df_jessie['club'] = df_jessie['club'].fillna("no-team-info")

In [ ]:
df_jessie.head(10)

,Unnamed: 0,tag,name,nameColor,icon,trophies,rank,club
0,0,#VL0GPPJV,Physic Gear 5,0xfff9c908,28000014,1401,1,Eclipse üåñ
1,1,#2Y92C2Q8V,NOMAD|„Åã„Éº„Åö„ÄÇ‚ùÑ‚ùÑ,0xfff9c908,28000119,1399,2,no-team-info
2,2,#VLQPVPY,Naz‚ù§Ô∏èHyra,0xffff8afb,28000303,1399,3,Fenernaz√ße üíôüíõ
3,3,#JQVQYVY,Code: VTzim üåë,0xffff8afb,28000339,1309,4,Eclipse üåñ
4,4,#RRVVPG2Y,BrostaÂç°Êãâ,0xff1ba5f5,28000206,1307,5,vMoove
5,5,#89UPQJJVV,+BraboX üé©,0xffa8e132,28000236,1302,6,Ghost Teamüëª‚òî
6,6,#VYGVV08Q,üçÖdomates,0xffffffff,28000261,1302,7,no-team-info
7,7,#2Y2Y99GQR,VizeZ,0xffffffff,28000230,1302,8,Ex0tic-E-Sport
8,8,#8GV2CP2J8,‚òîZORLU‚òî,0xffcb5aff,28000003,1301,9,<c0>Ôº¨ÔºØÔºÆÔº•Ôº¨Ôºπ‚òÖ</c>
9,9,#2G90YQ9CQ,∏·µó·¥ç…™ Ä·¥Ä…¥·¥Ö…™…¥ ú·¥Ä·µáÀ¢‰π°,0xffa8e132,28000174,1301,10,W·¥è ü“ì …¢·¥Ä…¥…¢ üêæ

In [7]:
# Drop the 'Unnamed: 0' column in place
df_jessie.drop(columns=['Unnamed: 0'], inplace=True)

---
* Data normalization:

In [8]:
# Initialize MinMaxScaler
scaler = MinMaxScaler()

# Normalize 'trophies' column
df_jessie['normalized_trophies'] = scaler.fit_transform(df_jessie[['trophies']])

In [9]:
# Normalize 'rank' column
df_jessie['normalized_rank'] = scaler.fit_transform(df_jessie[['rank']])

In [10]:
df_jessie.head(10)

,tag,name,nameColor,icon,trophies,rank,club,normalized_trophies,normalized_rank
0,#VL0GPPJV,Physic Gear 5,0xfff9c908,28000014,1401,1,Eclipse üåñ,1.000000,0.000000
1,#2Y92C2Q8V,NOMAD|„Åã„Éº„Åö„ÄÇ‚ùÑ‚ùÑ,0xfff9c908,28000119,1399,2,no-team-info,0.993289,0.005025
2,#VLQPVPY,Naz‚ù§Ô∏èHyra,0xffff8afb,28000303,1399,3,Fenernaz√ße üíôüíõ,0.993289,0.010050
3,#JQVQYVY,Code: VTzim üåë,0xffff8afb,28000339,1309,4,Eclipse üåñ,0.691275,0.015075
4,#RRVVPG2Y,BrostaÂç°Êãâ,0xff1ba5f5,28000206,1307,5,vMoove,0.684564,0.020101
5,#89UPQJJVV,+BraboX üé©,0xffa8e132,28000236,1302,6,Ghost Teamüëª‚òî,0.667785,0.025126
6,#VYGVV08Q,üçÖdomates,0xffffffff,28000261,1302,7,no-team-info,0.667785,0.030151
7,#2Y2Y99GQR,VizeZ,0xffffffff,28000230,1302,8,Ex0tic-E-Sport,0.667785,0.035176
8,#8GV2CP2J8,‚òîZORLU‚òî,0xffcb5aff,28000003,1301,9,<c0>Ôº¨ÔºØÔºÆÔº•Ôº¨Ôºπ‚òÖ</c>,0.664430,0.040201
9,#2G90YQ9CQ,∏·µó·¥ç…™ Ä·¥Ä…¥·¥Ö…™…¥ ú·¥Ä·µáÀ¢‰π°,0xffa8e132,28000174,1301,10,W·¥è ü“ì …¢·¥Ä…¥…¢ üêæ,0.664430,0.045226

---

* Data Exportation:

In [ ]:
# Export the DataFrame to the desired location
df_jessie.to_csv('../data/preprocessed/cleaned_jessie_ranking.csv', index=False)

--- 

</br>

# The bests 200 worldwide clubs dataframe

* Data import

In [11]:
df_club = pd.read_csv("../data/raw/dataset/global_club_info.csv")

In [ ]:
df_club.head(10)

,Unnamed: 0,tag,name,description,type,requiredTrophies,trophies,member_1_tag,member_1_name,member_1_role,...,member_28_role,member_28_trophies,member_29_tag,member_29_name,member_29_role,member_29_trophies,member_30_tag,member_30_name,member_30_role,member_30_trophies
0,0,#2YYJJV9PC,7 Dwarves,Remaining 7 eSports. Creator Code SuperLab. üá∫üá∏...,closed,35000,2210359,#90RQYP98U,‚ô°‚Ä¢bestie‚Ä¢‚ô°üß∏,senior,...,senior,62874.0,#JUQ2JVV8,Orlando‚ó¢‚ó§,senior,61407.0,#QQ0Y9PC,R7 | SPARTAN,president,50470.0
1,1,#2GUU9908V,BC*|Family*,üìçOfficial 3v3 Club of eSports Org @BerlinCityC...,inviteOnly,35000,2196794,#29L028GQL,Djahsta,senior,...,member,67596.0,#P0RQVQ00,‚òÖPERRY|‰Ω©Èáå üñ§,member,66352.0,#8JJQJYYL0,BC*| ‚ô°SŒöŒ≥LiŒ∑e,president,59503.0
2,2,#29CPP0R9G,Brawl King's,"Official Brawl Kings club, join our dc: RWs2wb...",inviteOnly,35000,2188358,#P99QGPLU2,Davex,member,...,member,70296.0,#9PG92YPVG,RX|JeanüíÆ,senior,64882.0,NaN,NaN,NaN,NaN
3,3,#2RVVLYR0G,Ex0tic-E-Sport,Ë¥∞ | Exotic Clan üèÜ - Actif Ldc Qdc üçπ - Master üéñ...,inviteOnly,35000,2157846,#GRLUYG0R,NiceSh√∏t üåì,member,...,member,67992.0,#Q928UCV0,‰πÇœÖœÑŒøœÅŒπŒµ„ÉÑ,member,66874.0,#P0YRJUURG,Ë°ô | Garnerio üåô,president,29259.0
4,4,#2C0GL8J0U,üßÄMUSSARELOS‚ú®,TAG: üßÄ|. Clube TOP 01 COMBATE DUPLO‚Ä¶Push insan...,inviteOnly,35000,2062393,#28LYUL8JP,ùô≤ùöòùöçùöéÀ¢À£‚ù•ùôπen,vicePresident,...,member,60888.0,#PYGLQPQCQ,NarutinBoladao,member,60432.0,#828UC8VRC,ninja sortudo‚Ñ¢Ô∏è,member,60316.0
5,5,#2GYQLVJPV,‚òÖthe Players‚òÖ,‚òÖMestres desde in√≠cio‚òÖ‚Ä°‚òÖRespeito‚òÖUni√£o‚òÖAmizade...,inviteOnly,35000,2054937,#20CJVQQYU,[‚ÇÆ‚Ç±] ‚Ç±…Ü‚±†‚Ç≥∆â‚Ç≥√ò,vicePresident,...,member,58770.0,#R8PVQ0U,ùìúùì≤ùì±ùì™ùìªùì™ ü¶¢,member,57558.0,#2YV98LLCY,"Arc,Lüåí",member,56951.0
6,6,#29U82J9YP,Kings United,ü•∂Kings United‚ñ™Ô∏éTropa do 3v3üé≠‚ñ™Ô∏éMega Pigüêñ‚ñ™Ô∏éTwich...,closed,35000,2036070,#98L9G0JVJ,·µê ≥ùëÄ èùë†ùë°ùëíùëü è„Ç∑,member,...,member,64255.0,#229UCQ9PY,4K·µá ≥ | Sude,member,62321.0,#2R2R89V9Y,ÊÑõ|Mitador BSüñ§,vicePresident,57500.0
7,7,#2C0VCC0RC,CONEXI√ìN,"üî•CODE: GUILLEVGXüî• CHARLIE, DE VERDAD QUE SENTI...",closed,35000,2020208,#8PJRRG2C,SK|GuilleVGX,president,...,member,59509.0,#808Y2G0L2,„Äé…¢–µ…¥…ë ÄŒ∫…™…¥…¢süí§„Äè,member,57089.0,#GVCJQRJG,Mr_Jose,senior,39482.0
8,8,#29CJUG0JJ,LA Global,+65k üáπüá∑1üåé1,inviteOnly,35000,1985296,#2JLU8PJLV,Einheit|Phil,member,...,senior,62647.0,#YVPVGLCP,Unlegit|Hydraüêç,member,53808.0,#PP2R9YVP8,R√Æchie„É£,president,37386.0
9,9,#282RJGGGY,WOLFMX,üá≤üáΩTOPüá≤üáΩ|DC Y WSP|‚ò†Ô∏èüê∫‚ò†Ô∏è |+60K,inviteOnly,35000,1984379,#GCGYLL0G,·¥µ·¥¨·¥π·¥∑Õ¢Õ¢Õ¢‚Å± ≥·µÉ,member,...,senior,59132.0,#P0YJP9RV0,„ÅÇ| ùòπLÃ∂“Ω·¥è19‚ÜØ,vicePresident,56536.0,#20UC0CQ8J,BMX | Akiüñ§,senior,51716.0

In [ ]:
df_club.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Columns: 127 entries, Unnamed: 0 to member_30_trophies
dtypes: float64(3), int64(30), object(94)
memory usage: 198.6+ KB

In [ ]:
df_club.columns

Index(['Unnamed: 0', 'tag', 'name', 'description', 'type', 'requiredTrophies',
       'trophies', 'member_1_tag', 'member_1_name', 'member_1_role',
       ...
       'member_28_role', 'member_28_trophies', 'member_29_tag',
       'member_29_name', 'member_29_role', 'member_29_trophies',
       'member_30_tag', 'member_30_name', 'member_30_role',
       'member_30_trophies'],
      dtype='object', length=127)

In [ ]:
df_club.describe

<bound method NDFrame.describe of      Rank         tag            name  \
0       0  #2YYJJV9PC       7 Dwarves
1       1  #2GUU9908V     BC*|Family*
2       2  #29CPP0R9G    Brawl King's
3       3  #2RVVLYR0G  Ex0tic-E-Sport
4       4  #2C0GL8J0U    üßÄMUSSARELOS‚ú®
..    ...         ...             ...
195   195  #280RUJ8VR  Kremenets City
196   196  #29RG2J022   ATM‚òîÔ∏è|Teamüî•‚ö°Ô∏è
197   197    #QPYYCQC   BrawlConQueso
198   198   #UQ8VQCYG     BLITZ Elite
199   199  #2G8CJP0QU   Fire‚ù§Ô∏è‚Äçüî•Brawl

                                           description        type  \
0    Remaining 7 eSports. Creator Code SuperLab. üá∫üá∏...      closed
1    üìçOfficial 3v3 Club of eSports Org @BerlinCityC...  inviteOnly
2    Official Brawl Kings club, join our dc: RWs2wb...  inviteOnly
3    Ë¥∞ | Exotic Clan üèÜ - Actif Ldc Qdc üçπ - Master üéñ...  inviteOnly
4    TAG: üßÄ|. Clube TOP 01 COMBATE DUPLO‚Ä¶Push insan...  inviteOnly
..                                                 ...         ...
195  –í—Ö–æ–¥ –æ—Ç 58–∫ üèÜ Megapig full üê∑ –ù–µ –∏–≥—Ä–∞–µ—à—å –∫–æ–ø–∏–ª–∫...  inviteOnly
196  <c9>Bienvenue</c> Dans <c9>ATM‚òîÔ∏è|Teamüî•‚ö°Ô∏è</c>|A...  inviteOnly
197  Solo para aut√©nticos QUESOS!|discord.gg/bcq|Li...  inviteOnly
198  <c5>‚ù¶Ô∏éBLITZ Elite Fam‚ù¶Ô∏é</c>Home of best 3v3 pl...  inviteOnly
199  Welcome To <c2>Fire‚ù§Ô∏è‚Äçüî•Brawl</c> |3v3 club|Fre...  inviteOnly

     requiredTrophies  trophies member_1_tag    member_1_name  member_1_role  \
0               35000   2210359   #90RQYP98U      ‚ô°‚Ä¢bestie‚Ä¢‚ô°üß∏         senior
1               35000   2196794   #29L028GQL          Djahsta         senior
2               35000   2188358   #P99QGPLU2            Davex         member
3               35000   2157846    #GRLUYG0R       NiceSh√∏t üåì         member
4               35000   2062393   #28LYUL8JP       ùô≤ùöòùöçùöéÀ¢À£‚ù•ùôπen  vicePresident
..                ...       ...          ...              ...            ...
195             35000   1693305   #2JUU2C0J9  |FR|Frozelina‚ù§Ô∏è         senior
196             35000   1692993   #2LRQP88GL      Áãó|√òùìá‚ÑòùíΩùì™‚Ñµ‚òîÔ∏èíÜú         member
197             35000   1692663     #YRUVJ8G        ‚ûºùó£…™·¥õ·¥á·¥ú‚Å∞‚Å∑ü¶¶         member
198             35000   1692194    #C029YCGG          üíÄmaheküíÄ         senior
199             35000   1691996    #VCY9P0YC           gusher  vicePresident

     ...  member_28_role member_28_trophies member_29_tag  member_29_name  \
0    ...          senior            62874.0     #JUQ2JVV8       Orlando‚ó¢‚ó§
1    ...          member            67596.0     #P0RQVQ00     ‚òÖPERRY|‰Ω©Èáå üñ§
2    ...          member            70296.0    #9PG92YPVG        RX|JeanüíÆ
3    ...          member            67992.0     #Q928UCV0        ‰πÇœÖœÑŒøœÅŒπŒµ„ÉÑ
4    ...          member            60888.0    #PYGLQPQCQ  NarutinBoladao
..   ...             ...                ...           ...             ...
195  ...          senior            52620.0    #PGV8990VR  inst:komar_hub
196  ...          member            52374.0    #8YG229YCR    ATM‚òî|Ninjaüî•‚ö°
197  ...          member            55369.0     #RPJG0VYL    „Äé iMBoBy „ÄèÈ∑πü¶Ö
198  ...   vicePresident            52223.0    #2VRPLVQUC           shyam
199  ...          member            46490.0      #2L2RLLU       ItzJack‚öúÔ∏è

     member_29_role member_29_trophies   member_30_tag   member_30_name  \
0            senior            61407.0        #QQ0Y9PC     R7 | SPARTAN
1            member            66352.0      #8JJQJYYL0    BC*| ‚ô°SŒöŒ≥LiŒ∑e
2            senior            64882.0  no-team-member   no-team-member
3            member            66874.0      #P0YRJUURG   Ë°ô | Garnerio üåô
4            member            60432.0      #828UC8VRC  ninja sortudo‚Ñ¢Ô∏è
..              ...                ...             ...              ...
195       president            52408.0  no-team-member   no-team-member
196       president            51284.0      #2LJ00CQY2  ‚ÜØ∆äeŒ±dÕé‚Ñìy‚ù¶N√©oxis
197   vicePresident            54745.0  no-team-member   no-team-member
198   vicePresident            51440.0      #2RGCG9VYQ       ùë´ùíÇùíõùíÇùíä|ÎßàÌîºÏïÑ‚ù¶
199          member            45955.0      #982G29VJG           Avenge

     member_30_role member_30_trophies
0         president            50470.0
1         president            59503.0
2    no-team-member     no-team-member
3         president            29259.0
4            member            60316.0
..              ...                ...
195  no-team-member     no-team-member
196          senior            50453.0
197  no-team-member     no-team-member
198          senior            51023.0
199          senior            45509.0

[200 rows x 127 columns]>

---
* Data Cleaning:

In [12]:
# Check for missing values per column
null_values = df_club.isnull().sum()
print("Missing values per column:\n", null_values)

# Check for total missing values in the entire dataset
total_nulls = df_club.isnull().sum().sum()
print(f'Total missing values in the dataset: {total_nulls}')

Missing values per column:
 Unnamed: 0             0
tag                    0
name                   0
description            1
type                   0
                      ..
member_29_trophies     9
member_30_tag         39
member_30_name        39
member_30_role        39
member_30_trophies    39
Length: 127, dtype: int64
Total missing values in the dataset: 201

In [13]:
# Replace null values in the 'description' column with "no-description"
df_club['description'] = df_club['description'].fillna("no-description")

# Replace null values in all other columns with "no-team-member"
df_club = df_club.fillna("no-team-member")

In [14]:
# Display rows where 'description' is "no-description"
df_club[df_club['description'] == 'no-description']

,Unnamed: 0,tag,name,description,type,requiredTrophies,trophies,member_1_tag,member_1_name,member_1_role,...,member_28_role,member_28_trophies,member_29_tag,member_29_name,member_29_role,member_29_trophies,member_30_tag,member_30_name,member_30_role,member_30_trophies
182,182,#2GP8899V8,Talents,no-description,closed,0,1698880,#YRURQRPUR,Skibidi Chipz,member,...,member,31424.0,#9ULY82RG0,Talent,president,7569.0,no-team-member,no-team-member,no-team-member,no-team-member

In [15]:
# Rename the column 'Unnamed: 0' to 'Rank'
df_club = df_club.rename(columns={'Unnamed: 0': 'Rank'})

In [16]:
df_club.head(10)

,Rank,tag,name,description,type,requiredTrophies,trophies,member_1_tag,member_1_name,member_1_role,...,member_28_role,member_28_trophies,member_29_tag,member_29_name,member_29_role,member_29_trophies,member_30_tag,member_30_name,member_30_role,member_30_trophies
0,0,#2YYJJV9PC,7 Dwarves,Remaining 7 eSports. Creator Code SuperLab. üá∫üá∏...,closed,35000,2210359,#90RQYP98U,‚ô°‚Ä¢bestie‚Ä¢‚ô°üß∏,senior,...,senior,62874.0,#JUQ2JVV8,Orlando‚ó¢‚ó§,senior,61407.0,#QQ0Y9PC,R7 | SPARTAN,president,50470.0
1,1,#2GUU9908V,BC*|Family*,üìçOfficial 3v3 Club of eSports Org @BerlinCityC...,inviteOnly,35000,2196794,#29L028GQL,Djahsta,senior,...,member,67596.0,#P0RQVQ00,‚òÖPERRY|‰Ω©Èáå üñ§,member,66352.0,#8JJQJYYL0,BC*| ‚ô°SŒöŒ≥LiŒ∑e,president,59503.0
2,2,#29CPP0R9G,Brawl King's,"Official Brawl Kings club, join our dc: RWs2wb...",inviteOnly,35000,2188358,#P99QGPLU2,Davex,member,...,member,70296.0,#9PG92YPVG,RX|JeanüíÆ,senior,64882.0,no-team-member,no-team-member,no-team-member,no-team-member
3,3,#2RVVLYR0G,Ex0tic-E-Sport,Ë¥∞ | Exotic Clan üèÜ - Actif Ldc Qdc üçπ - Master üéñ...,inviteOnly,35000,2157846,#GRLUYG0R,NiceSh√∏t üåì,member,...,member,67992.0,#Q928UCV0,‰πÇœÖœÑŒøœÅŒπŒµ„ÉÑ,member,66874.0,#P0YRJUURG,Ë°ô | Garnerio üåô,president,29259.0
4,4,#2C0GL8J0U,üßÄMUSSARELOS‚ú®,TAG: üßÄ|. Clube TOP 01 COMBATE DUPLO‚Ä¶Push insan...,inviteOnly,35000,2062393,#28LYUL8JP,ùô≤ùöòùöçùöéÀ¢À£‚ù•ùôπen,vicePresident,...,member,60888.0,#PYGLQPQCQ,NarutinBoladao,member,60432.0,#828UC8VRC,ninja sortudo‚Ñ¢Ô∏è,member,60316.0
5,5,#2GYQLVJPV,‚òÖthe Players‚òÖ,‚òÖMestres desde in√≠cio‚òÖ‚Ä°‚òÖRespeito‚òÖUni√£o‚òÖAmizade...,inviteOnly,35000,2054937,#20CJVQQYU,[‚ÇÆ‚Ç±] ‚Ç±…Ü‚±†‚Ç≥∆â‚Ç≥√ò,vicePresident,...,member,58770.0,#R8PVQ0U,ùìúùì≤ùì±ùì™ùìªùì™ ü¶¢,member,57558.0,#2YV98LLCY,"Arc,Lüåí",member,56951.0
6,6,#29U82J9YP,Kings United,ü•∂Kings United‚ñ™Ô∏éTropa do 3v3üé≠‚ñ™Ô∏éMega Pigüêñ‚ñ™Ô∏éTwich...,closed,35000,2036070,#98L9G0JVJ,·µê ≥ùëÄ èùë†ùë°ùëíùëü è„Ç∑,member,...,member,64255.0,#229UCQ9PY,4K·µá ≥ | Sude,member,62321.0,#2R2R89V9Y,ÊÑõ|Mitador BSüñ§,vicePresident,57500.0
7,7,#2C0VCC0RC,CONEXI√ìN,"üî•CODE: GUILLEVGXüî• CHARLIE, DE VERDAD QUE SENTI...",closed,35000,2020208,#8PJRRG2C,SK|GuilleVGX,president,...,member,59509.0,#808Y2G0L2,„Äé…¢–µ…¥…ë ÄŒ∫…™…¥…¢süí§„Äè,member,57089.0,#GVCJQRJG,Mr_Jose,senior,39482.0
8,8,#29CJUG0JJ,LA Global,+65k üáπüá∑1üåé1,inviteOnly,35000,1985296,#2JLU8PJLV,Einheit|Phil,member,...,senior,62647.0,#YVPVGLCP,Unlegit|Hydraüêç,member,53808.0,#PP2R9YVP8,R√Æchie„É£,president,37386.0
9,9,#282RJGGGY,WOLFMX,üá≤üáΩTOPüá≤üáΩ|DC Y WSP|‚ò†Ô∏èüê∫‚ò†Ô∏è |+60K,inviteOnly,35000,1984379,#GCGYLL0G,·¥µ·¥¨·¥π·¥∑Õ¢Õ¢Õ¢‚Å± ≥·µÉ,member,...,senior,59132.0,#P0YJP9RV0,„ÅÇ| ùòπLÃ∂“Ω·¥è19‚ÜØ,vicePresident,56536.0,#20UC0CQ8J,BMX | Akiüñ§,senior,51716.0

---

* Normalization:

In [17]:
# Normalize the 'trophies' column
df_club['trophies_normalized'] = scaler.fit_transform(df_club[['trophies']])

# Normalize the 'requiredTrophies' column
df_club['requiredTrophies_normalized'] = scaler.fit_transform(df_club[['requiredTrophies']])

In [18]:
df_club.head()

,Rank,tag,name,description,type,requiredTrophies,trophies,member_1_tag,member_1_name,member_1_role,...,member_29_tag,member_29_name,member_29_role,member_29_trophies,member_30_tag,member_30_name,member_30_role,member_30_trophies,trophies_normalized,requiredTrophies_normalized
0,0,#2YYJJV9PC,7 Dwarves,Remaining 7 eSports. Creator Code SuperLab. üá∫üá∏...,closed,35000,2210359,#90RQYP98U,‚ô°‚Ä¢bestie‚Ä¢‚ô°üß∏,senior,...,#JUQ2JVV8,Orlando‚ó¢‚ó§,senior,61407.0,#QQ0Y9PC,R7 | SPARTAN,president,50470.0,1.000000,1.0
1,1,#2GUU9908V,BC*|Family*,üìçOfficial 3v3 Club of eSports Org @BerlinCityC...,inviteOnly,35000,2196794,#29L028GQL,Djahsta,senior,...,#P0RQVQ00,‚òÖPERRY|‰Ω©Èáå üñ§,member,66352.0,#8JJQJYYL0,BC*| ‚ô°SŒöŒ≥LiŒ∑e,president,59503.0,0.975592,1.0
2,2,#29CPP0R9G,Brawl King's,"Official Brawl Kings club, join our dc: RWs2wb...",inviteOnly,35000,2188358,#P99QGPLU2,Davex,member,...,#9PG92YPVG,RX|JeanüíÆ,senior,64882.0,no-team-member,no-team-member,no-team-member,no-team-member,0.960413,1.0
3,3,#2RVVLYR0G,Ex0tic-E-Sport,Ë¥∞ | Exotic Clan üèÜ - Actif Ldc Qdc üçπ - Master üéñ...,inviteOnly,35000,2157846,#GRLUYG0R,NiceSh√∏t üåì,member,...,#Q928UCV0,‰πÇœÖœÑŒøœÅŒπŒµ„ÉÑ,member,66874.0,#P0YRJUURG,Ë°ô | Garnerio üåô,president,29259.0,0.905512,1.0
4,4,#2C0GL8J0U,üßÄMUSSARELOS‚ú®,TAG: üßÄ|. Clube TOP 01 COMBATE DUPLO‚Ä¶Push insan...,inviteOnly,35000,2062393,#28LYUL8JP,ùô≤ùöòùöçùöéÀ¢À£‚ù•ùôπen,vicePresident,...,#PYGLQPQCQ,NarutinBoladao,member,60432.0,#828UC8VRC,ninja sortudo‚Ñ¢Ô∏è,member,60316.0,0.733761,1.0

--- 

* Data Exportation:

In [ ]:
df_club.to_csv('../data/preprocessed/cleaned_club_ranking.csv', index=False)

---

# Best 200 clubs in Mexico Dataframe

* Data Import:

In [19]:
df_mexico_clubs = pd.read_csv("../data/raw/dataset/country_club_rankings/Mexico_club_rankings.csv")

In [ ]:
df_mexico_clubs.head(10)

,Unnamed: 0,tag,name,badgeId,trophies,rank,memberCount
0,0,#2G0UCPY80,–ë—É—Ä—ã–π –ú–µ–¥–≤–µ–¥—å,8000021,4026880,1,30
1,1,#282RJGGGY,WOLFMX,8000016,1984538,2,30
2,2,#2CLCYL202,Moonlight üßöüèª,8000052,1833116,3,30
3,3,#2GU9902G0,ÂÆ∂DarkMoon|üñ§,8000055,1775840,4,30
4,4,#29JRP22G9,HeadShoterZüí£,8000023,1773993,5,30
5,5,#C09LG8YL,minuta:3,8000035,1752235,6,30
6,6,#2RCQ9CGQQ,STMN Esports,8000015,1697266,7,29
7,7,#2GURLVQ29,AT|GALAXY XI,8000010,1696536,8,30
8,8,#QRVJP92R,Brawl Con Lim√≥n,8000039,1670500,9,30
9,9,#Q8J09VPQ,AxE Gaming,8000027,1670097,10,30

In [20]:
df_mexico_clubs = df_mexico_clubs[df_mexico_clubs['Unnamed: 0'] != 0]

In [21]:
# Delete the column "rank"
df_mexico_clubs.drop(columns=['rank'], inplace=True)

# Rename the column 'Unnamed: 0' to 'Rank'
df_mexico_clubs = df_mexico_clubs.rename(columns={'Unnamed: 0': 'Rank'})

In [ ]:
df_mexico_clubs

     Rank         tag           name  badgeId  trophies  memberCount
1       1  #282RJGGGY         WOLFMX  8000016   1984538           30
2       2  #2CLCYL202   Moonlight üßöüèª  8000052   1833116           30
3       3  #2GU9902G0    ÂÆ∂DarkMoon|üñ§  8000055   1775840           30
4       4  #29JRP22G9   HeadShoterZüí£  8000023   1773993           30
5       5   #C09LG8YL       minuta:3  8000035   1752235           30
..    ...         ...            ...      ...       ...          ...
195   195  #20RPQYU2V   Team Leyenda  8000059   1186442           30
196   196   #V0RUVPJ2     Pumas MXüá≤üáΩ  8000015   1185142           30
197   197  #2P2JRLP2L  Legi√≥n Kaktus  8000013   1185087           30
198   198   #9GVPLPRG      M√âXICANOS  8000013   1184301           30
199   199   #PRC0U80G      üá≤EXICO ‚úîÔ∏è  8000029   1182991           30

[199 rows x 6 columns]

---

* Data Cleaning:

In [22]:
# Check for missing values per column
null_values = df_mexico_clubs.isnull().sum()
print("Missing values per column:\n", null_values)

# Check for total missing values in the entire dataset
total_nulls = df_mexico_clubs.isnull().sum().sum()
print(f'Total missing values in the dataset: {total_nulls}')

Missing values per column:
 Rank           0
tag            0
name           0
badgeId        0
trophies       0
memberCount    0
dtype: int64
Total missing values in the dataset: 0

Fortunately, this dataset is cleaned.

---

* Data normalization:

In [23]:
# Normalize the 'trophies' column
df_mexico_clubs['trophies_normalized'] = scaler.fit_transform(df_mexico_clubs[['trophies']])

# Normalize the 'requiredTrophies' column
df_mexico_clubs['member_count_normalized'] = scaler.fit_transform(df_mexico_clubs[['memberCount']])

In [24]:
df_mexico_clubs.head(10)

,Rank,tag,name,badgeId,trophies,memberCount,trophies_normalized,member_count_normalized
1,1,#282RJGGGY,WOLFMX,8000016,1984538,30,1.000000,1.0
2,2,#2CLCYL202,Moonlight üßöüèª,8000052,1833116,30,0.811088,1.0
3,3,#2GU9902G0,ÂÆ∂DarkMoon|üñ§,8000055,1775840,30,0.739631,1.0
4,4,#29JRP22G9,HeadShoterZüí£,8000023,1773993,30,0.737327,1.0
5,5,#C09LG8YL,minuta:3,8000035,1752235,30,0.710182,1.0
6,6,#2RCQ9CGQQ,STMN Esports,8000015,1697266,29,0.641603,0.8
7,7,#2GURLVQ29,AT|GALAXY XI,8000010,1696536,30,0.640692,1.0
8,8,#QRVJP92R,Brawl Con Lim√≥n,8000039,1670500,30,0.608210,1.0
9,9,#Q8J09VPQ,AxE Gaming,8000027,1670097,30,0.607707,1.0
10,10,#2RGV8QCJR,LEGENDARYS,8000029,1668577,29,0.605811,0.8

--- 

* Data Exportation:

In [ ]:
df_mexico_clubs.to_csv("../data/preprocessed/cleaned_mexico_clubs_ranking.csv")

--- 

* Changes:
    1. Jessie Top 200 players:
        * Missed values replaced (No-club-info)
        * "Unnamed: 0" column deleted
        * "trophies" and "rank" columns scaled in min-max
    2. Global clubs ranking:
        * Missed values replaced (Description as "no-description" and if there had not been a team member, inserted "no-team-member")
        * "Unnamed: 0" column replaced by "rank"
        * "trophies" and "trophiesrequired" columns normalized by scaling min-max
    3. Top 200 Mexican Clubs:
        * There were neither missed nor repeated values
        * "Unnamed: 0" column replaced by "rank"
        * "trophies" and "trophiesrequired" columns normalized by scaling min-max

In [28]:
# Data_sets info:

df_jessie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   tag                  200 non-null    object
 1   name                 200 non-null    object
 2   nameColor            200 non-null    object
 3   icon                 200 non-null    int64
 4   trophies             200 non-null    int64
 5   rank                 200 non-null    int64
 6   club                 200 non-null    object
 7   normalized_trophies  200 non-null    float64
 8   normalized_rank      200 non-null    float64
dtypes: float64(2), int64(3), object(4)
memory usage: 14.2+ KB

In [30]:
df_club.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Columns: 129 entries, Rank to requiredTrophies_normalized
dtypes: float64(2), int64(30), object(97)
memory usage: 201.7+ KB

In [31]:
df_mexico_clubs.info()

<class 'pandas.core.frame.DataFrame'>
Index: 199 entries, 1 to 199
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Rank                     199 non-null    int64
 1   tag                      199 non-null    object
 2   name                     199 non-null    object
 3   badgeId                  199 non-null    int64
 4   trophies                 199 non-null    int64
 5   memberCount              199 non-null    int64
 6   trophies_normalized      199 non-null    float64
 7   member_count_normalized  199 non-null    float64
dtypes: float64(2), int64(4), object(2)
memory usage: 14.0+ KB